GET http://localhost:3001/listvaksin


###


POST http://localhost:3001/listvaksin
Content-Type: application/json

{
    "id": "AMGR779465",
    "Name": "Amalia Medical Center VGR",
    "Latitude": -6.246196939,
    "Longitude": 106.8677409
}


###

GET http://localhost:3001/listplasma


###


POST https://kebal-api.herokuapp.com/listplasma
Content-Type: application/json

{
"berat": "90",
"goldar": "A",
"hamil": "sudah",
"id": "OIN9P",
"jk": "pria",
"latitude": -6.20934577920955,
"longitude": 106.86054828140189,
"nama": "Octavianus Fin",
"pernah-covid": "sudah",
"rhesus": "+",
"sembuh-covid": "sudah",
"transfusi": "sudah",
"usia": "23",
}